# -*- coding: utf-8 -*-
"""yolo11_speed_esimation_training.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/gist/NANInithin/d343a20cddcb5acd9dcd1d55c0f4297c/yolo11_speed_esimation_training.ipynb
"""

# Commented out IPython magic to ensure Python compatibility.
# %pip install ultralytics
import ultralytics
ultralytics.checks()
from google.colab import drive
drive.mount('/content/drive')

gpu_info = !nvidia-smi
gpu_info = '\n'.join(gpu_info)
if gpu_info.find('failed') >= 0:
  print('Not connected to a GPU')
else:
  print(gpu_info)

from ultralytics import YOLO
model = YOLO("yolo11n.pt")
results = model.train(data="VisDrone.yaml", epochs=100, imgsz=640, lr0=0.01, batch=16)